ludus:
  - vm_name: "{{ range_id }}-ubuntu-eset-server"
    hostname: "eset-server"
    template: ubuntu-24.04-x64-server-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    linux: true
    domain:
      fqdn: eset.local
      role: member
    roles:
      - linux-domain-join
      - install-eset

  - vm_name: "{{ range_id }}-eee-esa"
    hostname: "SRV01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 21
    ram_gb: 6
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: eset.local
      role: primary-dc
    roles:
      - windows-setup
      - install-java
      - download-eset-esa-eee

  - vm_name: "{{ range_id }}-member-server"
    hostname: "SRV02"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 22
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: eset.local
      role: member
    roles:
      - windows-setup
      - install-eset-bridge-rds
