[Interface]
PrivateKey = sASSHIEik+cKsjhJMmltQfq+Ngy9FNSFHJerGIMVEEM=
Address = 198.51.100.2/32

[Peer]
PublicKey = nLM1wIG+1YMxQVd19zG5wJ7BWwJaxylYs2hhsgucjmk=
Endpoint = 192.168.1.161:51820
AllowedIPs = 10.2.0.0/16, 198.51.100.1/32
PersistentKeepalive = 25
