---
galaxy_info:
  author: Ralph Brynard
  description: Disable Windows security restrictions and install Chocolatey
  company: Bad Sector Labs
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2022
        - 11
  galaxy_tags:
    - windows
    - security
    - chocolatey
dependencies: []
