galaxy_info:
  author: Ralph Brynard
  description: Modifies ESET Agent ProductInstanceID UUID in registry
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2022
        - 11
dependencies: []
