---
# Download directory for ESET installers
eset_download_dir: "C:\\ESET_Installers"

# ESET Inspector download URL and filename
eset_inspector_url: "https://download.eset.com/com/eset/apps/business/eei/server/latest/ei_server_nt64.msi"
eset_inspector_filename: "ei_server_nt64.msi"
