---
galaxy_info:
  author: Ralph Brynard
  description: Configure Active Directory users and group memberships
  company: Bad Sector Labs
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2022
  galaxy_tags:
    - windows
    - active_directory
    - domain
dependencies: []
